"""
title: 🚑 Mermaid Doctor
version: 0.1.3
author: Hannibal
[https://github.com/annibale-x/open-webui-mermaid-doctor](https://github.com/annibale-x/open-webui-mermaid-doctor)
author_email: annibale.x@gmail.com
author_url: [https://openwebui.com/u/h4nn1b4l](https://openwebui.com/u/h4nn1b4l)
description: Heals broken Mermaid diagrams generated by small or hallucinating models.
"""

import re
from pydantic import BaseModel, Field
from typing import Optional

FEW_SHOTS_TEMPLATE = """
--- EXAMPLES OF CORRECT MERMAID SYNTAX ---
⚠️ CRITICAL: ALWAYS start ```mermaid on a NEW LINE.

⚠️ CRITICAL ER DIAGRAM RULES:
- Relationship definitions (e.g., A ||--o{ B : relates) must be OUTSIDE entity blocks {}.
- Entity blocks {} must ONLY contain attributes (e.g., string name).
- DO NOT nest relationships inside curly braces.

* graph TD
    A("Process Start") -->|"Initialize"| B{"Validation"}
    B -->|"Invalid?"| C["Wait / Retry"]
    C -->|"Re-check"| B
    B -->|"Valid?"| D["Core Execution!"]
    D --> E{"Integrity Check"}
    E -->|"Critical Error"| F["System Reset"]
    F --> A
    E -->|"Success"| G("End: Goal Reached")
* graph LR
    A("Source") -->|"Extract"| B("Processing")
    B -->|"Load"| C("Destination")    
* mindmap
  root((Main Concept))
    Problems
      Fragile syntax
      No parentheses in labels
    Solutions
      Very specific prompt
        Rigid system prompt
* erDiagram
  ENTITY_A ||--o{ ENTITY_B : contains
  ENTITY_A {
    string id
    int count
  }
* pie
    title Key Distribution
    "Chrome" :69
    "Safari" :16
    "Edge" :5
    "Firefox" :2
    "Others" :8
* gantt
    title Project Timeline
    dateFormat YYYY-MM-DD
    section Phase 1
    Analysis      :a1, 2024-01-01, 5d
    Design        :a2, after a1, 3d
    section Phase 2
    Coding        :active, a3, after a2, 10d
    Test Milestone :milestone, m1, after a3, 0d
"""


class Filter:

    class UserValves(BaseModel):
        enabled: bool = Field(
            default=True,
            description="Enable or disable the Mermaid Doctor filter transparently.",
        )
        inject_few_shots: bool = Field(
            default=True,
            description="Injects Mermaid few-shots into the prompt to guide micromodels and reduce hallucinations.",
        )
        inject_as_system_prompt: bool = Field(
            default=False,
            description="If enabled, injects the few-shots as a System prompt. If disabled, appends them to the last User prompt.",
        )
        strip_styles: bool = Field(
            default=True,
            description="Removes model-hallucinated colors, styles, and classDefs to keep UI consistent.",
        )

    def __init__(self):
        """
        Initialize the MITM Filter with empty sessions and load valves.
        """

        self.valves = self.UserValves()
        self.sessions = {}

    def _get_valves(self, __user__: Optional[dict] = None) -> BaseModel:
        """
        Safely retrieves the UserValves from the __user__ dictionary if available,
        otherwise falls back to the default singleton valves.
        """

        # Spacing rule: empty line before if
        if __user__ and "valves" in __user__ and __user__["valves"]:

            valves = __user__["valves"]

            # Spacing rule: empty line before if
            if isinstance(valves, self.UserValves):

                return valves

            # Spacing rule: empty line before elif
            elif isinstance(valves, dict):

                # Spacing rule: empty line before try
                try:

                    return self.UserValves(**valves)

                # Spacing rule: empty line before except
                except:

                    pass

        return self.valves

    def inlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """
        Intercepts the incoming request to verify if the filter is enabled and reset session state.
        Dynamically handles the injection of few-shots based on UserValves.
        """

        valves = self._get_valves(__user__)

        # Spacing rule: empty line before if
        if not valves.enabled:

            return body

        user_id = __user__.get("id", "default") if __user__ else "default"

        # Total reset of the operating room
        self.sessions[user_id] = {
            "full_text": "",
            "is_inside": False,
            "buffer": "",
            "out_buffer": "",
            "bypass": True,
        }

        messages = body.get("messages", [])

        # Spacing rule: empty line before if
        if not messages:

            return body

        # Filter is enabled: Disable bypass
        self.sessions[user_id]["bypass"] = False

        # Spacing rule: empty line before if
        if valves.inject_few_shots:

            # Spacing rule: empty line before if
            if valves.inject_as_system_prompt:

                # Insert as a system message at the beginning
                body["messages"].insert(
                    0, {"role": "system", "content": FEW_SHOTS_TEMPLATE}
                )

            # Spacing rule: empty line before else
            else:

                last_msg = body["messages"][-1]

                # Spacing rule: empty line before if
                if last_msg.get("role") == "user":

                    last_msg["content"] += f"\n\n{FEW_SHOTS_TEMPLATE}"

        return body

    def stream(self, event: dict, __user__: Optional[dict] = None) -> dict:
        """
        The core Man-in-the-Middle state machine for token streaming.
        Uses a pre-buffer (out_buffer) to lookbehind and fix glued tags in real-time.
        O(1) passthrough if bypass is active.
        """

        valves = self._get_valves(__user__)

        # Spacing rule: empty line before if
        if not valves.enabled:

            return event

        user_id = __user__.get("id", "default") if __user__ else "default"

        # Setup safety session
        # Spacing rule: empty line before if
        if user_id not in self.sessions:

            self.sessions[user_id] = {
                "full_text": "",
                "is_inside": False,
                "buffer": "",
                "out_buffer": "",
                "bypass": True,
            }

        session = self.sessions[user_id]

        # O(1) Non-invasive passthrough
        # Spacing rule: empty line before if
        if session["bypass"]:

            return event

        choices = event.get("choices", [])

        # Spacing rule: empty line before if
        if not choices:

            return event

        content = choices[0].get("delta", {}).get("content", "")

        # Spacing rule: empty line before if
        if not content:

            return event

        # 1. Update the global response memory
        session["full_text"] += content

        # --- STATE TRANSITION MANAGEMENT ---
        # Spacing rule: empty line before if
        if session["is_inside"]:

            session["buffer"] += content

            # Check if we exited the block
            # Spacing rule: empty line before if
            if "```" in session["buffer"]:

                session["is_inside"] = False

                parts = session["buffer"].split("```", 1)
                raw_mermaid = parts[0]
                remainder = parts[1] if len(parts) > 1 else ""

                sanitized = self._sanitize_mermaid(raw_mermaid, valves)

                # Check if the code was actually changed by the Doctor
                # We strip newlines/spaces for a fair comparison of the core logic
                # Spacing rule: empty line before if
                if sanitized.strip() != raw_mermaid.strip():

                    sanitized = (
                        "\n%% 💉 Sanitized by Mermaid Doctor 💉 %%\n" + sanitized
                    )

                event["choices"][0]["delta"]["content"] = sanitized + "\n```\n"

                session["buffer"] = ""
                session["out_buffer"] = remainder

            # Spacing rule: empty line before else
            else:

                event["choices"][0]["delta"]["content"] = ""

        # Spacing rule: empty line before else
        else:

            session["out_buffer"] += content
            lower_out = session["out_buffer"].lower()

            # TRANSITION A: Entering a Mermaid block
            # Spacing rule: empty line before if
            if "```mermaid" in lower_out:

                session["is_inside"] = True

                idx = lower_out.find("```mermaid")
                before_mermaid = session["out_buffer"][:idx]
                mermaid_tag = session["out_buffer"][idx : idx + 10]
                after_mermaid = session["out_buffer"][idx + 10 :]

                global_before = session["full_text"][
                    : -len(session["out_buffer"]) + idx
                ]

                # Check lookbehind: If the text just before the tag doesn't end with a newline, inject one!
                # Spacing rule: empty line before if
                if global_before and not global_before.endswith("\n"):

                    before_mermaid += "\n"

                event["choices"][0]["delta"]["content"] = (
                    before_mermaid + mermaid_tag + "\n"
                )

                session["out_buffer"] = ""
                session["buffer"] = after_mermaid

            # Still outside, hold back the pre-buffer window to avoid un-curable leaks
            # Spacing rule: empty line before else
            else:

                # Spacing rule: empty line before if
                if len(session["out_buffer"]) > 15:

                    safe_chunk = session["out_buffer"][:-15]
                    session["out_buffer"] = session["out_buffer"][-15:]
                    event["choices"][0]["delta"]["content"] = safe_chunk

                # Spacing rule: empty line before else
                else:

                    event["choices"][0]["delta"]["content"] = ""

        return event

    def outlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """
        Post-processing hook. Ensures that if the stream is abruptly cut off,
        any trapped text or diagram in the buffers is safely flushed.
        """

        valves = self._get_valves(__user__)

        # Spacing rule: empty line before if
        if not valves.enabled:

            return body

        user_id = __user__.get("id", "default") if __user__ else "default"

        # Spacing rule: empty line before if
        if user_id in self.sessions:

            session = self.sessions[user_id]

            # Spacing rule: empty line before if
            if not session.get("bypass"):

                messages = body.get("messages", [])

                # Spacing rule: empty line before if
                if messages:

                    last_msg = messages[-1]

                    # Spacing rule: empty line before if
                    if isinstance(last_msg.get("content"), str):

                        # Flush inside-buffer (safely sanitize remaining diagram)
                        # Spacing rule: empty line before if
                        if session.get("is_inside") and session.get("buffer"):

                            raw_mermaid = session["buffer"]
                            sanitized = self._sanitize_mermaid(raw_mermaid, valves)

                            # Spacing rule: empty line before if
                            if sanitized.strip() != raw_mermaid.strip():

                                sanitized = (
                                    "\n%% 💉 Sanitized by Mermaid Doctor 💉 %%\n"
                                    + sanitized
                                )

                            last_msg["content"] += "\n" + sanitized + "\n```\n"

                        # Flush outside-buffer (spill the 15 held chars)
                        # Spacing rule: empty line before elif
                        elif not session.get("is_inside") and session.get("out_buffer"):

                            last_msg["content"] += session["out_buffer"]

            # Clean up the operating room
            del self.sessions[user_id]

        return body

    def _sanitize_mermaid(self, raw_code: str, valves: BaseModel) -> str:
        """
        Cleans and enforces Mermaid syntax.
        Routes to specific sanitizers based on graph type.
        """

        # Replace non-breaking spaces (\xa0) with standard spaces
        code = raw_code.replace("\xa0", " ").strip()

        # Eradicate hallucinated task numbers at the start of the block (e.g., "1. graph TD" -> "graph TD")
        code = re.sub(r"^\s*\d+[\.\)\-]\s*", "", code)

        code_lower = code.lower()

        # Spacing rule: empty line before if
        if "mindmap" in code_lower:

            code = self._sterilize_mindmap(code)

        # Spacing rule: empty line before elif
        elif "graph " in code_lower:

            code = self._sterilize_graph(code, valves)

        # Spacing rule: empty line before elif
        elif "erdiagram" in code_lower:

            code = self._sterilize_er(code)

        # Spacing rule: empty line before elif
        elif "pie" in code_lower:

            code = self._sterilize_pie(code)

        # Spacing rule: empty line before elif
        elif "gantt" in code_lower:

            code = self._sterilize_gantt(code)

        return "\n" + code + "\n"

    def _sterilize_gantt(self, block: str) -> str:
        """
        Fixes Gantt charts corrupted by micromodels.
        Completely reassembles Task lines to ensure correct Mermaid parsing logic:
        [status], [id], [start_date | after id], [duration]
        """

        lines = block.split("\n")
        cleaned_lines = []

        # Pass 1: Re-assemble fragmented lines
        for line in lines:

            stripped = line.strip()

            # Spacing rule: empty line before if
            if (
                not stripped
                or stripped.lower() in ["```mermaid", "```", "gantt"]
                or stripped.lower().startswith(
                    ("title ", "section ", "%%", "dateformat", "axisformat")
                )
            ):

                cleaned_lines.append(line)
                continue

            # If the line starts with a colon, it's a fragmented task data line
            # Spacing rule: empty line before if
            if stripped.startswith(":"):

                # Spacing rule: empty line before if
                if cleaned_lines and not cleaned_lines[-1].strip().lower().startswith(
                    (
                        "section",
                        "title",
                        "gantt",
                        "```",
                        "%%",
                        "dateformat",
                        "axisformat",
                    )
                ):

                    cleaned_lines[-1] = cleaned_lines[-1] + " " + stripped
                    continue

            # If the previous line ended with a colon, this line is probably the continuation
            # Spacing rule: empty line before if
            if cleaned_lines and cleaned_lines[-1].strip().endswith(":"):

                # Spacing rule: empty line before if
                if not stripped.lower().startswith(
                    (
                        "section",
                        "title",
                        "gantt",
                        "```",
                        "%%",
                        "dateformat",
                        "axisformat",
                    )
                ):

                    cleaned_lines[-1] = cleaned_lines[-1] + " " + stripped
                    continue

            cleaned_lines.append(line)

        # Pass 2: Clean up intra-line syntax using a universal re-assembler
        task_counter = 0

        for i, line in enumerate(cleaned_lines):

            stripped = line.strip()

            # Spacing rule: empty line before if
            if not stripped or stripped.lower().startswith(
                ("gantt", "title ", "section ", "```", "%%", "dateformat", "axisformat")
            ):

                continue

            # Spacing rule: empty line before if
            if line.count(":") >= 1:

                parts = line.split(":")
                title = " - ".join(p.strip() for p in parts[:-1]).strip()
                data = parts[-1].strip()

                # Eradicate hallucinated 'dur' prefixes
                data = re.sub(
                    r"\bdur\s+(\d+[smhdwM])", r"\1", data, flags=re.IGNORECASE
                )

                # Safe split of data properties
                # Spacing rule: empty line before if
                if "," not in data:

                    raw_parts = data.split()

                # Spacing rule: empty line before else
                else:

                    raw_parts = [p.strip() for p in data.split(",")]

                status_part = None
                id_part = None
                start_part = None
                duration_part = None

                # Dissect and categorize each property
                for p in raw_parts:

                    p = p.strip()
                    p_lower = p.lower()

                    # Spacing rule: empty line before if
                    if p_lower in ["active", "done", "crit", "milestone"]:

                        status_part = p_lower

                    # Spacing rule: empty line before elif
                    elif re.match(r"^\d+[smhdwM]$", p):

                        duration_part = p

                    # Spacing rule: empty line before elif
                    elif re.match(r"^\d{4}-\d{2}-\d{2}$", p):

                        # Spacing rule: empty line before try
                        try:

                            # Basic validation to prevent hallucinations like 2024-01-33
                            d_parts = p.split("-")

                            # Spacing rule: empty line before if
                            if (
                                1 <= int(d_parts[1]) <= 12
                                and 1 <= int(d_parts[2]) <= 31
                            ):

                                start_part = p

                        # Spacing rule: empty line before except
                        except:

                            pass

                    # Spacing rule: empty line before elif
                    elif p_lower.startswith("after"):

                        # Spacing rule: empty line before if
                        if p_lower == "after":

                            start_part = "after_placeholder"  # Orphaned 'after' caught!

                        # Spacing rule: empty line before else
                        else:

                            start_part = p

                    # Spacing rule: empty line before else
                    else:

                        # Fallback for ID recognition
                        # Spacing rule: empty line before if
                        if not id_part and re.match(r"^[a-zA-Z0-9_]+$", p):

                            id_part = p

                task_counter += 1

                # Auto-assign missing IDs
                current_id = id_part if id_part else f"task{task_counter}"

                # Auto-chain missing or orphaned starts
                # Spacing rule: empty line before if
                if start_part == "after_placeholder" or not start_part:

                    start_part = (
                        f"after task{task_counter-1}"
                        if task_counter > 1
                        else "2024-01-01"
                    )

                # Standardize durations (prevent crashes from empty durations)
                # Spacing rule: empty line before if
                if not duration_part:

                    duration_part = "0d" if status_part == "milestone" else "1d"

                # Reassemble strictly in Mermaid Gantt format
                new_data_parts = []

                # Spacing rule: empty line before if
                if status_part:

                    new_data_parts.append(status_part)

                new_data_parts.append(current_id)
                new_data_parts.append(start_part)
                new_data_parts.append(duration_part)

                new_data = ", ".join(new_data_parts)
                indent = line[: len(line) - len(line.lstrip())]
                cleaned_lines[i] = f"{indent}{title} : {new_data}"

        return "\n".join(cleaned_lines)

    def _sterilize_pie(self, block: str) -> str:
        """
        Fixes Pie charts corrupted by syntax hallucinations.
        Converts assignment operators '=' to ':' and extracts labels
        from hallucinated graph node syntax (e.g., ID[Label] : value).
        """

        lines = block.split("\n")
        cleaned_lines = []

        for line in lines:

            stripped = line.strip()

            # Spacing rule: empty line before if
            if (
                not stripped
                or stripped.lower() in ["```mermaid", "```", "pie"]
                or stripped.lower().startswith("title ")
            ):

                cleaned_lines.append(line)
                continue

            # Spacing rule: empty line before if
            if ":" in stripped or "=" in stripped:

                normalized = stripped.replace("=", ":")
                parts = normalized.split(":", 1)
                raw_label = parts[0].strip()
                value = parts[1].strip()

                node_match = re.match(
                    r'^[A-Za-z0-9_]*\s*[\[\(]\s*"?([^"\]\)]+)"?\s*[\]\)]$', raw_label
                )

                # Spacing rule: empty line before if
                if node_match:

                    raw_label = node_match.group(1).strip()

                raw_label = raw_label.strip("\"'")

                indent = line[: len(line) - len(line.lstrip())]
                line = f'{indent}"{raw_label}" : {value}'

            cleaned_lines.append(line)

        return "\n".join(cleaned_lines)

    def _sterilize_er(self, block: str) -> str:
        """
        Fixes ER diagrams corrupted by 'graph' syntax hallucinations,
        UML class syntax hallucinations, glued relationships, and relationships
        hallucinated inside attribute blocks.
        """

        lines = block.split("\n")
        cleaned_lines = []
        in_entity_block = False

        for line in lines:

            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Spacing rule: empty line before if
            if (
                not stripped
                or lower_stripped in ["```mermaid", "```"]
                or lower_stripped.startswith("title ")
                or lower_stripped.startswith("%%")
            ):

                cleaned_lines.append(line)
                continue

            # Force strict normalization of the ER diagram declaration line
            # Spacing rule: empty line before if
            if lower_stripped.startswith("erdiagram"):

                cleaned_lines.append("erDiagram")
                continue

            # Fix hallucinated sequence/flowchart AND UML inheritance arrows (e.g. -->>, ->, ---|>)
            line = re.sub(
                r"([A-Za-z0-9_]+)\s*(?:-->>|-->|->|-\.>|\.\.>|=>|==>|-{1,3}\|>)\s*([A-Za-z0-9_]+)",
                r"\1 ||--o{ \2",
                line,
            )

            # Fix hallucinated mixed-line relations (e.g. ||--|..|) containing both solid and dashed elements
            line = re.sub(
                r"([A-Za-z0-9_]+)\s*(?:[\}o\|]*--[\}o\|]*\.\.[\}o\|]*|[\}o\|]*\.\.[\}o\|]*--[\}o\|]*)\s*([A-Za-z0-9_]+)",
                r"\1 ||--o{ \2",
                line,
            )

            is_relationship = bool(re.search(r"[\}o\|]*(?:--|\.\.)[o\|\{]*", line))

            # Spacing rule: empty line before if
            if is_relationship:

                # Spacing rule: empty line before if
                if in_entity_block:

                    indent = line[: len(line) - len(line.lstrip())]
                    cleaned_lines.append(indent + "}")
                    in_entity_block = False

                def _clean_entity(match):

                    entity_name = match.group(2)
                    return re.sub(r"\s+", "_", entity_name.strip())

                line = re.sub(
                    r'([A-Za-z0-9_]+)\s*[\[\(]\s*"?([^"\]\)]+)"?[\]\)]?',
                    _clean_entity,
                    line,
                )

                line = re.sub(r"([\}o\|]+)\s*(--|\.\.)\s*([o\|\{]+)", r"\1\2\3", line)

                # Extended fix for hallucinated extra pipes and hybrid cardinalities
                for bad, good in [
                    ("}||", "}|"),
                    ("||{", "|{"),
                    ("}o|", "}o"),
                    ("|o{", "o{"),
                    ("o|{", "o{"),
                    ("}|o", "}o"),
                    ("o||", "o|"),
                    ("||o", "|o"),
                ]:

                    line = line.replace(bad, good)

                line = re.sub(
                    r"([A-Za-z0-9_]+)\s*([\}o\|]*(?:--|\.\.)[o\|\{]*)\s*([A-Za-z0-9_]+)",
                    r"\1 \2 \3",
                    line,
                )

                # Fix unquoted relationship labels with spaces or force missing labels
                # Spacing rule: empty line before if
                if ":" not in line:

                    line = line.rstrip() + " : relates_to"

                # Spacing rule: empty line before else
                else:

                    parts = line.split(":", 1)
                    rel_label = parts[1].strip().strip("\"'")
                    rel_label = re.sub(r"\s+", "_", rel_label)

                    # Spacing rule: empty line before if
                    if not rel_label:

                        rel_label = "relates_to"

                    line = f"{parts[0].rstrip()} : {rel_label}"

                cleaned_lines.append(line)
                continue

            # Spacing rule: empty line before if
            if "{" in stripped:

                in_entity_block = True

            is_closing = "}" in stripped

            # Spacing rule: empty line before if
            if in_entity_block and "{" not in stripped and not is_closing:

                # Spacing rule: empty line before if
                if any(
                    x in lower_stripped
                    for x in ["one-to-", "many-to-", "1:n", "n:m", "1:1", "->", "<-"]
                ):

                    continue

                # Spacing rule: empty line before if
                if ":" in stripped:

                    m = re.match(
                        r"^(\s*)([a-zA-Z0-9_]+)\s*:\s*([a-zA-Z0-9_]+)\s*$", line
                    )

                    # Spacing rule: empty line before if
                    if m:

                        line = f"{m.group(1)}{m.group(3)} {m.group(2)}"

                    # Spacing rule: empty line before else
                    else:

                        continue

                line = re.sub(r"^(\s*)[\+\-\~]\s*", r"\1", line)
                line = re.sub(
                    r"^(\s*)([a-zA-Z0-9_]+)\s+([a-zA-Z0-9_]+)\s*$", r"\1\3 \2", line
                )

                cleaned_lines.append(line)

                # Spacing rule: empty line before if
                if is_closing:

                    in_entity_block = False

                continue

            # Spacing rule: empty line before if
            if is_closing:

                in_entity_block = False

            title_match = re.match(
                r'^[A-Za-z0-9_]*\s*[\[\(]\s*"?([^"\]\)]+)"?[\]\)]?$', stripped
            )

            # Spacing rule: empty line before if
            if title_match:

                cleaned_lines.append(f'title "{title_match.group(1).strip()}"')
                continue

            cleaned_lines.append(line)

        # Spacing rule: empty line before if
        if in_entity_block:

            cleaned_lines.append("}")

        return "\n".join(cleaned_lines)

    def _sterilize_mindmap(self, block: str) -> str:
        """
        Smart sanitizer for Mermaid mindmaps.
        """

        lines = block.split("\n")
        cleaned_lines = []

        for line in lines:

            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Spacing rule: empty line before if
            if lower_stripped in ["```mermaid", "```"] or not stripped:

                cleaned_lines.append(line)
                continue

            # Spacing rule: empty line before if
            if lower_stripped.startswith("mindmap"):

                cleaned_lines.append("mindmap")
                continue

            # Spacing rule: empty line before if
            if stripped.startswith("root(") or stripped.startswith("root(("):

                cleaned_lines.append(line)
                continue

            indent = line[: len(line) - len(stripped)]
            safe_text = re.sub(r"^(?:[\|\+\-\*\>]\s*)+", "", stripped)

            # Spacing rule: empty line before if
            if not safe_text:

                continue

            safe_text = re.sub(r"(\*\*|__|\*)", "", safe_text)
            safe_text = safe_text.replace('"', "")
            safe_text = re.sub(r"[\(\[\{]", ' "', safe_text)
            safe_text = re.sub(r"[\)\]\}]", '" ', safe_text)
            safe_text = re.sub(r'("\s*")+', '"', safe_text)
            safe_text = re.sub(r"\s+", " ", safe_text).strip()

            cleaned_lines.append(f"{indent}{safe_text}")

        data_lines_info = []

        for i, line in enumerate(cleaned_lines):

            stripped = line.strip()

            # Spacing rule: empty line before if
            if stripped and stripped.lower() not in ["```mermaid", "```", "mindmap"]:

                indent_len = len(line) - len(stripped)
                data_lines_info.append((i, indent_len))

        # Spacing rule: empty line before if
        if data_lines_info:

            min_indent = min(info[1] for info in data_lines_info)
            root_count = sum(1 for info in data_lines_info if info[1] == min_indent)

            # Spacing rule: empty line before if
            if root_count > 1:

                first_idx = data_lines_info[0][0]
                master_indent = " " * max(0, min_indent - 2)
                cleaned_lines.insert(first_idx, f"{master_indent}root((Core Concept))")

                for i in range(first_idx + 1, len(cleaned_lines)):

                    line = cleaned_lines[i]
                    stripped = line.strip()

                    # Spacing rule: empty line before if
                    if stripped and stripped.lower() not in [
                        "```mermaid",
                        "```",
                        "mindmap",
                    ]:

                        cleaned_lines[i] = "  " + line

        return "\n".join(cleaned_lines)

    def _sterilize_graph(self, block: str, valves: BaseModel) -> str:
        """
        Fixes common trailing character hallucinations, space-in-ID issues,
        naked quoted nodes, and style stripping.
        """

        block = re.sub(
            r'graph_([a-zA-Z]{2})\s*\[\s*[\'"]graph\s+[a-zA-Z]{2}[\'"]\s*\]',
            r"graph \1",
            block,
            flags=re.IGNORECASE,
        )

        safe_block = re.sub(r'(\["[^"\]]+"\])\)', r"\1", block)
        safe_block = re.sub(r'(\("[^"\)]+"\))\]', r"\1", safe_block)

        safe_block = re.sub(
            r'-->\s*\|\s*"?([^|\]"]+)"?\s*\]',
            lambda m: f'-->NODE_{re.sub(r"[^a-zA-Z0-9]", "", m.group(1))[:10]}["{m.group(1)}"]',
            safe_block,
        )

        lines = safe_block.split("\n")
        cleaned_lines = []
        reserved_keywords = {
            "end",
            "subgraph",
            "click",
            "style",
            "class",
            "classdef",
            "linkstyle",
        }

        def _clean_node_part(work_part: str) -> str:

            work_part = work_part.strip()
            work_part = re.sub(r"(\*\*|__|\*)", "", work_part)

            for opener, closer in [("[", "]"), ("(", ")"), ("{", "}")]:

                # Spacing rule: empty line before if
                if work_part.endswith(closer) and opener not in work_part:

                    work_part = work_part[:-1].strip()

            # Spacing rule: empty line before if
            if (
                work_part.startswith('"')
                and work_part.endswith('"')
                and len(work_part) > 1
            ):

                inner_text = work_part[1:-1].strip()
                safe_gen_id = "N_" + re.sub(r"[^a-zA-Z0-9]", "", inner_text)[:10]
                return f'{safe_gen_id}["{inner_text}"]'

            node_match = re.match(r"^([^\[\(\{\>]+?)\s*([\[\(\{\>].*)?$", work_part)

            # Spacing rule: empty line before if
            if node_match:

                raw_id = node_match.group(1).strip()
                label_block = node_match.group(2) or ""

                # Spacing rule: empty line before if
                if label_block:

                    opener = label_block[0]
                    bracket_map = {"[": "]", "(": ")", "{": "}", ">": "]"}

                    # Spacing rule: empty line before if
                    if opener in bracket_map:

                        expected_closer = bracket_map[opener]

                        # Spacing rule: empty line before if
                        if not label_block.endswith(expected_closer):

                            label_block = (
                                label_block.rstrip(")]}\"' ") + expected_closer
                            )

                    # Enforce quotes around inner text to prevent Mermaid parser crashes on '()' or extra spaces
                    shape_match = re.match(
                        r"^([\[\(\{\>]+[\/\\]?)\s*[\"']?(.*?)[\"']?\s*([\/\\]?[\]\)\}]+)$",
                        label_block,
                    )

                    # Spacing rule: empty line before if
                    if shape_match:

                        open_sym = shape_match.group(1)
                        inner_txt = shape_match.group(2).replace('"', "'")
                        close_sym = shape_match.group(3)
                        label_block = f'{open_sym}"{inner_txt}"{close_sym}'

                # Spacing rule: empty line before if
                if not label_block and " " in raw_id:

                    safe_id = re.sub(r"[^a-zA-Z0-9_]", "", re.sub(r"\s+", "_", raw_id))

                    # Spacing rule: empty line before if
                    if safe_id.lower() in reserved_keywords:

                        safe_id = f"ID_{safe_id}"

                    # Spacing rule: empty line before if
                    if not safe_id:

                        safe_id = "NODE"

                    return f'{safe_id}["{raw_id}"]'

                raw_id = raw_id.replace('"', "")
                safe_id = re.sub(r"\s+", "_", raw_id)
                safe_id = re.sub(r"[^a-zA-Z0-9_]", "", safe_id)

                # Spacing rule: empty line before if
                if not safe_id:

                    safe_id = "NODE"

                # Spacing rule: empty line before if
                if safe_id.lower() in reserved_keywords:

                    safe_id = f"ID_{safe_id}"

                return safe_id + label_block

            return work_part

        for line in lines:

            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Spacing rule: empty line before if
            if (
                not stripped
                or lower_stripped in ["```mermaid", "```"]
                or lower_stripped.startswith("graph ")
                or lower_stripped.startswith("%%")
            ):

                cleaned_lines.append(line)
                continue

            is_style_line = lower_stripped.startswith(
                ("style ", "classdef ", "click ", "linkstyle ", "class ")
            )

            # Spacing rule: empty line before if
            if is_style_line:

                # Spacing rule: empty line before if
                if getattr(valves, "strip_styles", True):

                    continue

                # Spacing rule: empty line before else
                else:

                    cleaned_lines.append(line)
                    continue

            # Spacing rule: empty line before if
            if lower_stripped.startswith("subgraph ") or lower_stripped == "end":

                cleaned_lines.append(line)
                continue

            leading_spaces = line[: len(line) - len(line.lstrip())]

            # Spacing rule: empty line before if
            if "-->" in line:

                parts = line.split("-->")
                new_parts = []

                for i, part in enumerate(parts):

                    work_part = part.strip()
                    has_semi = work_part.endswith(";")

                    # Spacing rule: empty line before if
                    if has_semi:

                        work_part = work_part[:-1].strip()

                    edge_label = ""
                    m1 = re.match(r'^\|\s*"([^"]+)"\s*\|?(.*)', work_part)
                    m2 = re.match(r"^\|([^|]+)\|(.*)", work_part)

                    # Spacing rule: empty line before if
                    if m1:

                        clean_inner = m1.group(1).strip()

                        # Spacing rule: empty line before if
                        if clean_inner:

                            clean_inner = re.sub(r"(\*\*|__|\*)", "", clean_inner)
                            edge_label = f'|"{clean_inner}"|'

                        work_part = m1.group(2).strip()

                    # Spacing rule: empty line before elif
                    elif m2:

                        clean_inner = m2.group(1).strip()

                        # Spacing rule: empty line before if
                        if clean_inner:

                            clean_inner = re.sub(r"(\*\*|__|\*)", "", clean_inner)
                            edge_label = f'|"{clean_inner}"|'

                        work_part = m2.group(2).strip()

                    cleaned_node = _clean_node_part(work_part)
                    reconstructed = edge_label + cleaned_node

                    # Spacing rule: empty line before if
                    if has_semi and i == len(parts) - 1:

                        reconstructed += ";"

                    # Spacing rule: empty line before if
                    if i == 0:

                        new_parts.append(leading_spaces + reconstructed)

                    # Spacing rule: empty line before else
                    else:

                        new_parts.append(reconstructed)

                cleaned_lines.append("-->".join(new_parts))

            # Spacing rule: empty line before else
            else:

                has_semi = stripped.endswith(";")
                work_part = stripped[:-1].strip() if has_semi else stripped
                cleaned_node = _clean_node_part(work_part)

                # Spacing rule: empty line before if
                if has_semi:

                    cleaned_node += ";"

                cleaned_lines.append(leading_spaces + cleaned_node)

        return "\n".join(cleaned_lines)
