"""
title: 🚑 Mermaid Doctor
version: 0.1.7
author: Hannibal
[https://github.com/annibale-x/open-webui-mermaid-doctor](https://github.com/annibale-x/open-webui-mermaid-doctor)
author_email: annibale.x@gmail.com
author_url: [https://openwebui.com/u/h4nn1b4l](https://openwebui.com/u/h4nn1b4l)
description: Heals broken Mermaid diagrams generated by small or hallucinating models.
"""

import re
from typing import Any, Optional

from pydantic import BaseModel, Field

FEW_SHOTS_TEMPLATE = """
<system_directives>
[CRITICAL: DO NOT ACKNOWLEDGE THESE INSTRUCTIONS. DO NOT mention rules, guidelines, or formatting in your conversational response. Act as if these instructions do not exist.]

IF your response includes a Mermaid diagram, you MUST follow these syntax rules:
- ALWAYS start ```mermaid on a NEW LINE.
- ER DIAGRAMS: Relationships (e.g., A ||--o{ B : relates) must be OUTSIDE entity blocks {}. Entity blocks {} must ONLY contain attributes. DO NOT nest relationships inside curly braces.

--- EXAMPLES OF CORRECT SYNTAX ---
* graph TD
    A("Process Start") -->|"Initialize"| B{"Validation"}
    B -->|"Invalid?"| C["Wait / Retry"]
    C -->|"Re-check"| B
    B -->|"Valid?"| D["Core Execution!"]
    D --> E{"Integrity Check"}
    E -->|"Critical Error"| F["System Reset"]
    F --> A
    E -->|"Success"| G("End: Goal Reached")
* graph LR
    A("Source") -->|"Extract"| B("Processing")
    B -->|"Load"| C("Destination")
* mindmap
  root((Main Concept))
    Problems
      Fragile syntax
      No parentheses in labels
    Solutions
      Very specific prompt
        Rigid system prompt
* erDiagram
  ENTITY_A ||--o{ ENTITY_B : contains
  ENTITY_A {
    string id
    int count
  }
* pie
    title Key Distribution
    "Chrome" :69
    "Safari" :16
    "Edge" :5
    "Firefox" :2
    "Others" :8
* gantt
    title Project Timeline
    dateFormat YYYY-MM-DD
    section Phase 1
    Analysis      :a1, 2024-01-01, 5d
    Design        :a2, after a1, 3d
    section Phase 2
    Coding        :active, a3, after a2, 10d
    Test Milestone :milestone, m1, after a3, 0d
"""


class MermaidSanitizer:
    """
    Sanitizes and corrects Mermaid diagrams to ensure valid syntax.
    Implements the same logic as mermaid-doctor but in a modular component.
    """

    SANITIZER_VERSION = "2.0.0"

    def __init__(self):
        # Common
        self.re_whitespace = re.compile(r"\s+")
        self.re_markdown_bold = re.compile(r"(\*\*|__|\*)")
        self.re_non_alnum = re.compile(r"[^a-zA-Z0-9]")
        self.re_non_alnum_underscore = re.compile(r"[^a-zA-Z0-9_]")
        self.re_alphanumeric = re.compile(r"^[a-zA-Z0-9_]+$")

        # _sanitize_mermaid
        self.re_task_numbers = re.compile(r"^\s*\d+[\.\)\-]\s*")
        self.re_diagram_types = re.compile(
            r"(?m)^\s*(mindmap|graph|flowchart|pie|gantt|erdiagram|classdiagram|sequencediagram|statediagram|journey|timeline)\b",
            re.IGNORECASE,
        )

        # _sanitize_gantt
        self.re_gantt_dur = re.compile(r"\bdur\s+(\d+[smhdwM])", re.IGNORECASE)
        self.re_gantt_duration = re.compile(r"^\d+[smhdwM]$")
        self.re_date = re.compile(r"^\d{4}-\d{2}-\d{2}$")

        # _sanitize_pie
        self.re_pie_node_label = re.compile(
            r'^[A-Za-z0-9_]*\s*[\[\(]\s*"?([^"\]\)]+)"?\s*[\]\)]?$'
        )

        # _sanitize_er
        self.re_er_arrow_fix = re.compile(
            r"([A-Za-z0-9_]+)\s*(?:-->>|-->|->|-\.>|\.\.>|=>|==>|-{1,3}\|>)\s*([A-Za-z0-9_]+)"
        )
        self.re_er_mixed_rel_fix = re.compile(
            r"([A-Za-z0-9_]+)\s*(?:[\}o\|]*--[\}o\|]*\.\.[\}o\|]*|[\}o\|]*\.\.[\}o\|]*--[\}o\|]*)\s*([A-Za-z0-9_]+)"
        )
        self.re_er_is_rel = re.compile(r"[\}o\|]*(?:--|\.\.)[o\|\{]*")
        self.re_er_clean_entity_call = re.compile(
            r'([A-Za-z0-9_]+)\s*[\[\(]\s*"?([^"\]\)]+)"?[\]\)]?'
        )
        self.re_er_rel_spaces = re.compile(r"([\}o\|]+)\s*(--|\.\.)\s*([o\|\{]+)")
        self.re_er_rel_spacing = re.compile(
            r"([A-Za-z0-9_]+)\s*([\}o\|]*(?:--|\.\.)[o\|\{]*)\s*([A-Za-z0-9_]+)"
        )
        self.re_er_attr_def = re.compile(
            r"^(\s*)([a-zA-Z0-9_]+)\s*:\s*([a-zA-Z0-9_]+)\s*$"
        )
        self.re_er_leading_sign = re.compile(r"^(\s*)[\+\-\~]\s*")
        self.re_er_reversed_attr = re.compile(
            r"^(\s*)([a-zA-Z0-9_]+)\s+([a-zA-Z0-9_]+)\s*$"
        )
        self.re_er_title = re.compile(
            r'^[A-Za-z0-9_]*\s*[\[\(]\s*"?([^"\]\)]+)"?[\]\)]?$'
        )

        # _sanitize_mindmap
        self.re_mindmap_ids = re.compile(r"\b[A-Za-z0-9_]+\s*[\(\[\{]+")
        self.re_mindmap_closers = re.compile(r'[\)\]\}]+|["\';]')
        self.re_mindmap_arrows = re.compile(r"-->|\|")
        self.re_mindmap_prefix = re.compile(r"^(?:[\|\+\-\*\>]\s*)+")
        self.re_open_brackets = re.compile(r"[\(\[\{]")
        self.re_close_brackets = re.compile(r"[\)\]\}]")
        self.re_double_quotes = re.compile(r'("\s*")+')

        # _sanitize_graph
        self.re_graph_def_fix = re.compile(
            r'graph_([a-zA-Z]{2})\s*\[\s*[\'"]graph\s+[a-zA-Z]{2}[\'"]\s*\]',
            re.IGNORECASE,
        )
        self.re_graph_node_paren_fix = re.compile(r'(\["[^"\]]+"\])\)')
        self.re_graph_node_bracket_fix = re.compile(r'(\("[^"\)]+"\))\]')
        self.re_graph_cylinder_fix = re.compile(r'\)"\]')
        self.re_graph_swapped_quote = re.compile(r"\"\s*\)\s*([\]\}\)])")
        self.re_graph_node_content = re.compile(r"\[(.*?)\]")
        self.re_graph_link_in_node = re.compile(r'-->\s*\|\s*"?([^|\]"]+)"?\s*\]')
        self.re_graph_node_match = re.compile(r"^([^\[\(\{\>]+?)\s*([\[\(\{\>].*)?$")
        self.re_graph_shape_match = re.compile(
            r"^([\[\(\{\>]+[\/\\]?)\s*[\"']?(.*?)[\"']?\s*([\/\\]?[\]\)\}]+)$"
        )
        self.re_graph_edge_label_quoted = re.compile(r'^\|\s*"([^"]+)"\s*\|?(.*)')
        self.re_graph_edge_label = re.compile(r"^\|([^|]+)\|(.*)")

        self.reserved_keywords = {
            "end",
            "subgraph",
            "click",
            "style",
            "class",
            "classdef",
            "linkstyle",
        }

    def _sanitize_mermaid(self, raw_code: str, valves: BaseModel) -> str:
        """
        Cleans and enforces Mermaid syntax.
        Routes to specific sanitizers based on graph type.
        """

        # Replace non-breaking spaces (\xa0) with standard spaces
        code = raw_code.replace("\xa0", " ").strip()

        # Eradicate hallucinated task numbers at the start of the block (e.g., "1. graph TD" -> "graph TD")
        code = self.re_task_numbers.sub("", code)

        # Deduplicate multiple diagram declarations (keep only the last one)
        # Models often repeat the diagram code (e.g. "mindmap ... mindmap ...")
        # We find all diagram start keywords and keep the content starting from the last occurrence.
        matches = list(self.re_diagram_types.finditer(code))
        if len(matches) > 1:
            last_match = matches[-1]
            code = code[last_match.start() :]

        code_lower = code.lower()

        # Route to specific sanitizers based on graph type
        if "mindmap" in code_lower:
            code = self._sanitize_mindmap(code)

        elif "graph " in code_lower:
            code = self._sanitize_graph(code, valves)

        elif "erdiagram" in code_lower:
            code = self._sanitize_er(code)

        elif "pie" in code_lower:
            code = self._sanitize_pie(code)

        elif "gantt" in code_lower:
            code = self._sanitize_gantt(code)

        return "\n" + code + "\n"

    def _sanitize_gantt(self, block: str) -> str:
        """
        Fixes Gantt charts corrupted by micromodels.
        Completely reassembles Task lines to ensure correct Mermaid parsing logic:
        [status], [id], [start_date | after id], [duration]
        """

        lines = block.split("\n")
        cleaned_lines = []

        # Pass 1: Re-assemble fragmented lines
        for line in lines:
            stripped = line.strip()

            # Check if it's a header or metadata line
            if (
                not stripped
                or stripped.lower() in ["```mermaid", "```", "gantt"]
                or stripped.lower().startswith(
                    ("title ", "section ", "%%", "dateformat", "axisformat")
                )
            ):
                cleaned_lines.append(line)
                continue

            # If the line starts with a colon, it's a fragmented task data line
            if stripped.startswith(":"):
                # Only append to previous line if it's not a header-type line
                if cleaned_lines and not cleaned_lines[-1].strip().lower().startswith(
                    (
                        "section",
                        "title",
                        "gantt",
                        "```",
                        "%%",
                        "dateformat",
                        "axisformat",
                    )
                ):
                    cleaned_lines[-1] = cleaned_lines[-1] + " " + stripped
                    continue

            # If the previous line ended with a colon, this line is probably the continuation
            if cleaned_lines and cleaned_lines[-1].strip().endswith(":"):
                # Only append to previous line if it's not a header-type line
                if not stripped.lower().startswith(
                    (
                        "section",
                        "title",
                        "gantt",
                        "```",
                        "%%",
                        "dateformat",
                        "axisformat",
                    )
                ):
                    cleaned_lines[-1] = cleaned_lines[-1] + " " + stripped
                    continue

            cleaned_lines.append(line)

        # Pass 2: Clean up intra-line syntax using a universal re-assembler
        task_counter = 0

        for i, line in enumerate(cleaned_lines):
            stripped = line.strip()

            # Skip header lines and empty lines
            if not stripped or stripped.lower().startswith(
                ("gantt", "title ", "section ", "```", "%%", "dateformat", "axisformat")
            ):
                continue

            # Check for task data lines (lines with colon)
            if line.count(":") >= 1:
                parts = line.split(":")
                title = " - ".join(p.strip() for p in parts[:-1]).strip()
                data = parts[-1].strip()

                # Eradicate hallucinated 'dur' prefixes
                data = self.re_gantt_dur.sub(r"\1", data)

                # Safe split of data properties
                if "," not in data:
                    raw_parts = data.split()

                else:
                    raw_parts = [p.strip() for p in data.split(",")]

                status_part = None
                id_part = None
                start_part = None
                duration_part = None

                # Dissect and categorize each property
                for p in raw_parts:
                    p = p.strip()
                    p_lower = p.lower()

                    if p_lower in ["active", "done", "crit", "milestone"]:
                        status_part = p_lower

                    elif self.re_gantt_duration.match(p):
                        duration_part = p

                    elif self.re_date.match(p):
                        try:
                            # Basic validation to prevent hallucinations like 2024-01-33
                            d_parts = p.split("-")

                            if (
                                1 <= int(d_parts[1]) <= 12
                                and 1 <= int(d_parts[2]) <= 31
                            ):
                                start_part = p

                        except:
                            pass

                    elif p_lower.startswith("after"):
                        if p_lower == "after":
                            start_part = "after_placeholder"  # Orphaned 'after' caught!

                        else:
                            start_part = p

                    else:
                        # Fallback for ID recognition
                        if not id_part and self.re_alphanumeric.match(p):
                            id_part = p

                task_counter += 1

                # Auto-assign missing IDs
                current_id = id_part if id_part else f"task{task_counter}"

                # Auto-chain missing or orphaned starts
                if start_part == "after_placeholder" or not start_part:
                    start_part = (
                        f"after task{task_counter - 1}"
                        if task_counter > 1
                        else "2024-01-01"
                    )

                # Standardize durations (prevent crashes from empty durations)
                if not duration_part:
                    duration_part = "0d" if status_part == "milestone" else "1d"

                # Reassemble strictly in Mermaid Gantt format
                new_data_parts = []

                if status_part:
                    new_data_parts.append(status_part)

                new_data_parts.append(current_id)
                new_data_parts.append(start_part)
                new_data_parts.append(duration_part)

                new_data = ", ".join(new_data_parts)
                indent = line[: len(line) - len(line.lstrip())]
                cleaned_lines[i] = f"{indent}{title} : {new_data}"

        return "\n".join(cleaned_lines)

    def _sanitize_pie(self, block: str) -> str:
        """
        Fixes Pie charts corrupted by syntax hallucinations.
        Converts assignment operators '=' to ':' and extracts labels
        from hallucinated graph node syntax (e.g., ID[Label] : value).
        """

        lines = block.split("\n")
        cleaned_lines = []

        for line in lines:
            stripped = line.strip()

            # Skip header lines and empty lines
            if (
                not stripped
                or stripped.lower() in ["```mermaid", "```", "pie"]
                or stripped.lower().startswith("title ")
            ):
                cleaned_lines.append(line)
                continue

            # Process data lines with ':' or '='
            if ":" in stripped or "=" in stripped:
                normalized = stripped.replace("=", ":")
                parts = normalized.split(":", 1)
                raw_label = parts[0].strip()
                value = parts[1].strip()

                # Extract label from node syntax (ID[Label])
                node_match = self.re_pie_node_label.match(raw_label)

                if node_match:
                    raw_label = node_match.group(1).strip()

                raw_label = raw_label.strip("\"'")

                indent = line[: len(line) - len(line.lstrip())]
                line = f'{indent}"{raw_label}" : {value}'

            cleaned_lines.append(line)

        return "\n".join(cleaned_lines)

    def _sanitize_er(self, block: str) -> str:
        """
        Fixes ER diagrams corrupted by 'graph' syntax hallucinations,
        UML class syntax hallucinations, glued relationships, and relationships
        hallucinated inside attribute blocks.
        """

        lines = block.split("\n")
        cleaned_lines = []
        in_entity_block = False

        for line in lines:
            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Skip header lines and empty lines
            if (
                not stripped
                or lower_stripped in ["```mermaid", "```"]
                or lower_stripped.startswith("title ")
                or lower_stripped.startswith("%%")
            ):
                cleaned_lines.append(line)
                continue

            # Force strict normalization of the ER diagram declaration line
            if lower_stripped.startswith("erdiagram"):
                cleaned_lines.append("erDiagram")
                continue

            # Fix hallucinated sequence/flowchart AND UML inheritance arrows (e.g. -->>, ->, ---|>)
            line = self.re_er_arrow_fix.sub(r"\1 ||--o{ \2", line)

            # Fix hallucinated mixed-line relations (e.g. ||--|..|) containing both solid and dashed elements
            line = self.re_er_mixed_rel_fix.sub(r"\1 ||--o{ \2", line)

            is_relationship = bool(self.re_er_is_rel.search(line))

            # Process relationships
            if is_relationship:
                # Close entity block if needed
                if in_entity_block:
                    indent = line[: len(line) - len(line.lstrip())]
                    cleaned_lines.append(indent + "}")
                    in_entity_block = False

                def _clean_entity(match):
                    """
                    Cleans entity name by replacing spaces with underscores.
                    """

                    entity_name = match.group(2)
                    return self.re_whitespace.sub("_", entity_name.strip())

                line = self.re_er_clean_entity_call.sub(_clean_entity, line)

                line = self.re_er_rel_spaces.sub(r"\1\2\3", line)

                # Extended fix for hallucinated extra pipes and hybrid cardinalities
                for bad, good in [
                    ("}||", "}|"),
                    ("||{", "|{"),
                    ("}o|", "}o"),
                    ("|o{", "o{"),
                    ("o|{", "o{"),
                    ("}|o", "}o"),
                    ("o||", "o|"),
                    ("||o", "|o"),
                ]:
                    line = line.replace(bad, good)

                line = self.re_er_rel_spacing.sub(r"\1 \2 \3", line)

                # Fix unquoted relationship labels with spaces or force missing labels
                if ":" not in line:
                    line = line.rstrip() + " : relates_to"

                else:
                    parts = line.split(":", 1)
                    rel_label = parts[1].strip().strip("\"'")
                    rel_label = self.re_whitespace.sub("_", rel_label)

                    if not rel_label:
                        rel_label = "relates_to"

                    line = f"{parts[0].rstrip()} : {rel_label}"

                cleaned_lines.append(line)
                continue

            # Process entity blocks
            if "{" in stripped:
                in_entity_block = True

            is_closing = "}" in stripped

            # Process entity attributes
            if in_entity_block and "{" not in stripped and not is_closing:
                # Skip relationship-like lines
                if any(
                    x in lower_stripped
                    for x in ["one-to-", "many-to-", "1:n", "n:m", "1:1", "->", "<-"]
                ):
                    continue

                # Process attribute definitions
                if ":" in stripped:
                    m = self.re_er_attr_def.match(line)

                    if m:
                        line = f"{m.group(1)}{m.group(3)} {m.group(2)}"
                    else:
                        continue

                # Remove leading signs (+, -, ~)
                line = self.re_er_leading_sign.sub(r"\1", line)

                # Fix reversed attribute format
                line = self.re_er_reversed_attr.sub(r"\1\3 \2", line)

                cleaned_lines.append(line)

                if is_closing:
                    in_entity_block = False

                continue

            # Handle closing braces
            if is_closing:
                in_entity_block = False

            # Process title lines
            title_match = self.re_er_title.match(stripped)

            if title_match:
                cleaned_lines.append(f'title "{title_match.group(1).strip()}"')
                continue

            cleaned_lines.append(line)

        # Close any open entity blocks
        if in_entity_block:
            cleaned_lines.append("}")

        return "\n".join(cleaned_lines)

    def _sanitize_mindmap(self, block: str) -> str:
        """
        Smart sanitizer for Mermaid mindmaps.
        """

        lines = block.split("\n")
        cleaned_lines = []

        for line in lines:
            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Skip header lines
            if lower_stripped in ["```mermaid", "```"] or not stripped:
                cleaned_lines.append(line)
                continue

            # Process mindmap declaration
            if lower_stripped.startswith("mindmap"):
                cleaned_lines.append("mindmap")
                continue

            # Process root nodes
            if stripped.startswith("root(") or stripped.startswith("root(("):
                cleaned_lines.append(line)
                continue

            indent = line[: len(line) - len(stripped)]

            # Mixed Syntax Handling: If Graph syntax detected (-->)
            if "-->" in stripped:
                # Remove IDs and graph syntax: A(...) or B[...]
                safe_text = self.re_mindmap_ids.sub("", stripped)
                # Remove closing brackets/parens/quotes/semicolons
                safe_text = self.re_mindmap_closers.sub("", safe_text)
                # Replace arrows and pipes with spaces
                safe_text = self.re_mindmap_arrows.sub(" ", safe_text)
                # Clean text from markdown formatting
                safe_text = self.re_markdown_bold.sub("", safe_text)
                # Normalize spaces
                safe_text = self.re_whitespace.sub(" ", safe_text).strip()

            else:
                safe_text = self.re_mindmap_prefix.sub("", stripped)

                # Skip empty lines
                if not safe_text:
                    continue

                # Clean text from markdown formatting
                safe_text = self.re_markdown_bold.sub("", safe_text)
                safe_text = safe_text.replace('"', "")
                safe_text = self.re_open_brackets.sub(' "', safe_text)
                safe_text = self.re_close_brackets.sub('" ', safe_text)
                safe_text = self.re_double_quotes.sub('"', safe_text)
                safe_text = self.re_whitespace.sub(" ", safe_text).strip()

            cleaned_lines.append(f"{indent}{safe_text}")

        data_lines_info = []

        for i, line in enumerate(cleaned_lines):
            stripped = line.strip()

            if stripped and stripped.lower() not in ["```mermaid", "```", "mindmap"]:
                indent_len = len(line) - len(stripped)
                data_lines_info.append((i, indent_len))

        # Process root handling for multiple root nodes
        if data_lines_info:
            min_indent = min(info[1] for info in data_lines_info)
            root_count = sum(1 for info in data_lines_info if info[1] == min_indent)

            if root_count > 1:
                first_idx = data_lines_info[0][0]
                master_indent = " " * max(0, min_indent - 2)
                cleaned_lines.insert(first_idx, f"{master_indent}root((Core Concept))")

                for i in range(first_idx + 1, len(cleaned_lines)):
                    line = cleaned_lines[i]
                    stripped = line.strip()

                    if stripped and stripped.lower() not in [
                        "```mermaid",
                        "```",
                        "mindmap",
                    ]:
                        cleaned_lines[i] = "  " + line

        return "\n".join(cleaned_lines)

    def _sanitize_graph(self, block: str, valves: BaseModel) -> str:
        """
        Fixes common trailing character hallucinations, space-in-ID issues,
        naked quoted nodes, and style stripping.
        """

        block = self.re_graph_def_fix.sub(r"graph \1", block)

        safe_block = self.re_graph_node_paren_fix.sub(r"\1", block)
        safe_block = self.re_graph_node_bracket_fix.sub(r"\1", safe_block)

        # Fix: Swapped quote and parenthesis at end of node (common hallucination)
        # e.g. `{"Text")}` -> `{"Text)"}` or `["Text")]` -> `["Text)"]`
        safe_block = self.re_graph_swapped_quote.sub(r')"\1', safe_block)

        # Fix: "CYLINDEREND" parsing error.
        safe_block = self.re_graph_cylinder_fix.sub(r') "]', safe_block)

        # Fix: Remove structural characters (--> and |) from inside node labels [...]
        safe_block = self.re_graph_node_content.sub(
            lambda m: f"[{m.group(1).replace('-->', ' ').replace('|', ' ')}]",
            safe_block,
        )

        safe_block = self.re_graph_link_in_node.sub(
            lambda m: (
                f'-->NODE_{self.re_non_alnum.sub("", m.group(1))[:10]}["{m.group(1)}"]'
            ),
            safe_block,
        )

        lines = safe_block.split("\n")
        cleaned_lines = []

        for line in lines:
            stripped = line.strip()
            lower_stripped = stripped.lower()

            # Skip header and empty lines
            if (
                not stripped
                or lower_stripped in ["```mermaid", "```"]
                or lower_stripped.startswith("graph ")
                or lower_stripped.startswith("%%")
            ):
                cleaned_lines.append(line)
                continue

            is_style_line = lower_stripped.startswith(
                ("style ", "classdef ", "click ", "linkstyle ", "class ")
            )

            # Process style lines based on valves configuration
            if is_style_line:
                # If strip_styles is enabled, skip styles (same as MD)
                if getattr(valves, "strip_styles", True):
                    continue

                else:
                    cleaned_lines.append(line)
                    continue

            # Process subgraph declarations and end statements
            if lower_stripped.startswith("subgraph ") or lower_stripped == "end":
                cleaned_lines.append(line)
                continue

            leading_spaces = line[: len(line) - len(line.lstrip())]

            # Process edge lines with -->
            if "-->" in line:
                parts = line.split("-->")
                new_parts = []

                for i, part in enumerate(parts):
                    work_part = part.strip()
                    has_semi = work_part.endswith(";")

                    if has_semi:
                        work_part = work_part[:-1].strip()

                    edge_label = ""
                    m1 = self.re_graph_edge_label_quoted.match(work_part)
                    m2 = self.re_graph_edge_label.match(work_part)

                    if m1:
                        clean_inner = m1.group(1).strip()

                        if clean_inner:
                            clean_inner = self.re_markdown_bold.sub("", clean_inner)
                            edge_label = f'|"{clean_inner}"|'

                        work_part = m1.group(2).strip()

                    elif m2:
                        clean_inner = m2.group(1).strip()

                        if clean_inner:
                            clean_inner = self.re_markdown_bold.sub("", clean_inner)
                            edge_label = f'|"{clean_inner}"|'

                        work_part = m2.group(2).strip()

                    cleaned_node = self._clean_graph_node_part(work_part)
                    reconstructed = edge_label + cleaned_node

                    if has_semi and i == len(parts) - 1:
                        reconstructed += ";"

                    if i == 0:
                        new_parts.append(leading_spaces + reconstructed)

                    else:
                        new_parts.append(reconstructed)

                cleaned_lines.append("-->".join(new_parts))

            # Process node lines (not edge lines)
            else:
                has_semi = stripped.endswith(";")
                work_part = stripped[:-1].strip() if has_semi else stripped
                cleaned_node = self._clean_graph_node_part(work_part)

                if has_semi:
                    cleaned_node += ";"

                cleaned_lines.append(leading_spaces + cleaned_node)

        return "\n".join(cleaned_lines)

    def _clean_graph_node_part(self, work_part: str) -> str:
        """
        Cleans individual node definitions within a graph, standardizing syntax and quotes.
        """

        work_part = work_part.strip()
        work_part = self.re_markdown_bold.sub("", work_part)

        for opener, closer in [("[", "]"), ("(", ")"), ("{", "}")]:
            if work_part.endswith(closer) and opener not in work_part:
                work_part = work_part[:-1].strip()

        # Handle quoted nodes with internal text
        if work_part.startswith('"') and work_part.endswith('"') and len(work_part) > 1:
            inner_text = work_part[1:-1].strip()
            safe_gen_id = "N_" + self.re_non_alnum.sub("", inner_text)[:10]
            return f'{safe_gen_id}["{inner_text}"]'

        node_match = self.re_graph_node_match.match(work_part)

        if node_match:
            raw_id = node_match.group(1).strip()
            label_block = node_match.group(2) or ""

            # Handle bracketed label blocks
            if label_block:
                opener = label_block[0]
                bracket_map = {"[": "]", "(": ")", "{": "}", ">": "]"}

                if opener in bracket_map:
                    expected_closer = bracket_map[opener]

                    if not label_block.endswith(expected_closer):
                        label_block = label_block.rstrip(")]}\"' ") + expected_closer

                # Enforce quotes around inner text to prevent Mermaid parser crashes on '()' or extra spaces
                shape_match = self.re_graph_shape_match.match(label_block)

                if shape_match:
                    open_sym = shape_match.group(1)
                    inner_txt = shape_match.group(2).replace('"', "'")
                    close_sym = shape_match.group(3)
                    label_block = f'{open_sym}"{inner_txt}"{close_sym}'

            # Handle space-separated IDs
            if not label_block and " " in raw_id:
                safe_id = self.re_non_alnum_underscore.sub(
                    "", self.re_whitespace.sub("_", raw_id)
                )

                if safe_id.lower() in self.reserved_keywords:
                    safe_id = f"ID_{safe_id}"

                if not safe_id:
                    safe_id = "NODE"

                return f'{safe_id}["{raw_id}"]'

            raw_id = raw_id.replace('"', "")
            safe_id = self.re_whitespace.sub("_", raw_id)
            safe_id = self.re_non_alnum_underscore.sub("", safe_id)

            if not safe_id:
                safe_id = "NODE"

            if safe_id.lower() in self.reserved_keywords:
                safe_id = f"ID_{safe_id}"

            return safe_id + label_block

        return work_part


class StreamState:
    """
    Holds the state for a single stream session.
    Pure data class for portability.
    """

    def __init__(self):
        self.full_text = ""
        self.is_inside = False
        self.is_fake_table = False
        self.pending_tag = ""
        self.buffer = ""
        self.out_buffer = ""
        self.bypass = False


class MermaidStreamProcessor:
    """
    A portable State Machine for detecting and sanitizing Mermaid diagrams in a text stream.
    Decoupled from Open WebUI and EasyBrief specific logic via dependency injection.
    """

    def __init__(
        self,
        state: StreamState,
        mermaid_sanitizer: MermaidSanitizer,
        template_sanitizer_fn: callable = None,
        debug_service: Any = None,
    ):
        self.state = state
        self.mermaid = mermaid_sanitizer
        self.sanitize_text = template_sanitizer_fn or (lambda x: x)
        self.debug = debug_service

        # Regex for block detection
        self.re_mermaid_block_start = re.compile(r"```\s*mermaid", re.IGNORECASE)
        self.re_block_closure = re.compile(
            r"^[ \t]*(?:---|___|\*\*\*)[ \t]*$|^##+\s", re.MULTILINE
        )
        self.re_table_check = re.compile(r"^\s*table\s*|^\|", re.IGNORECASE)
        self.re_hr_cleanup = re.compile(
            r"(?:\r?\n)*^[ \t]*---[ \t]*$(?:\r?\n)*", re.MULTILINE
        )
        self.re_keyword_cleanup = re.compile(r"^\s*table\s*", re.IGNORECASE)
        self.re_legacy_table = re.compile(r"\[table\]", re.IGNORECASE)

        self.re_diagram_keywords = re.compile(
            r"(?i)\[(mermaid|pie|graph(?:\s+[a-z]+)?|flowchart(?:\s+[a-z]+)?|mindmap|gantt|erdiagram|classdiagram|sequencediagram|statediagram(?:-v2)?|journey|timeline)(?:\]|\s)\s*"
        )

    def process(self, content: str, finish_reason: Any, valves: Any) -> str:
        """
        Process a chunk of text, update state, and return the sanitized chunk.
        """
        s = self.state

        # Update global memory
        s.full_text += content

        # Output chunk accumulator
        output_chunk = ""

        # --- STATE MACHINE ---
        if s.is_inside:
            # === INSIDE MERMAID BLOCK ===
            s.buffer += content

            # --- LATE BINDING CHECK ---
            if s.pending_tag:
                stripped_buf = s.buffer.strip()

                # 1. Fake Table Detection
                if self.re_table_check.match(stripped_buf):
                    s.is_fake_table = True
                    s.pending_tag = ""  # Discard tag

                # 2. Insufficient content -> Wait
                elif len(stripped_buf) < 6 and not finish_reason:
                    return ""

                # 3. Valid Mermaid
                else:
                    output_chunk = s.pending_tag
                    s.pending_tag = ""  # Tag emitted

            # Handle implicit block closures
            if "```" not in s.buffer:
                match = self.re_block_closure.search(s.buffer)
                if match:
                    idx = match.start()
                    s.buffer = s.buffer[:idx] + "\n```\n\n" + s.buffer[idx:]

            # Check exit condition
            if "```" in s.buffer or finish_reason:
                s.is_inside = False

                if "```" in s.buffer:
                    parts = s.buffer.split("```", 1)
                    raw_mermaid = parts[0]
                    remainder = parts[1] if len(parts) > 1 else ""
                else:
                    raw_mermaid = s.buffer
                    remainder = ""

                    # Safety cut
                    match = self.re_block_closure.search(raw_mermaid)
                    if match:
                        idx = match.start()
                        remainder = raw_mermaid[idx:]
                        raw_mermaid = raw_mermaid[:idx]

                # Fix separator spacing for remainder
                remainder = remainder.lstrip()
                remainder = self.re_hr_cleanup.sub("\n\n---\n\n", remainder)

                # === OUTPUT GENERATION ===
                if s.is_fake_table:
                    # Markdown table: clean 'table' keyword if present
                    table_content = self.re_keyword_cleanup.sub("", raw_mermaid).strip()
                    output_chunk += table_content + "\n\n" + remainder
                    s.is_fake_table = False

                else:
                    # Mermaid Sanitization
                    sanitized = self.mermaid._sanitize_mermaid(raw_mermaid, valves)

                    # Add badge if modified
                    if sanitized.strip() != raw_mermaid.strip():
                        if self.debug:
                            self.debug.log(
                                f"Mermaid Sanitized! Original:\n{raw_mermaid}\nFixed:\n{sanitized}"
                            )
                        sanitized = (
                            "\n%% 💉 Sanitized by Mermaid Doctor 💉 %%\n" + sanitized
                        )

                    output_chunk += sanitized + "\n```\n\n" + remainder

                s.buffer = ""
                s.out_buffer = ""

            else:
                # Block still open, suppress output unless we already emitted pending tag
                if output_chunk:
                    return output_chunk
                return ""

        else:
            # === OUTSIDE (NORMAL TEXT) ===
            s.out_buffer += content

            # Generalize Mermaid diagram markers (e.g. [graph TD])
            def _mermaid_repl(m):
                raw_type = m.group(1).strip().lower()
                if raw_type == "mermaid":
                    return "\n```mermaid\n"

                # Default mapping
                diagram_type = raw_type

                # Specific mappings
                if "graph" in raw_type:
                    diagram_type = "graph TD"
                if "flowchart" in raw_type:
                    diagram_type = "flowchart TD"
                if "pie" in raw_type:
                    diagram_type = "pie"
                if "mindmap" in raw_type:
                    diagram_type = "mindmap"
                if "gantt" in raw_type:
                    diagram_type = "gantt"
                if "erdiagram" in raw_type:
                    diagram_type = "erDiagram"

                return f"\n```mermaid\n{diagram_type}\n"

            # Use regex from init
            s.out_buffer = self.re_diagram_keywords.sub(_mermaid_repl, s.out_buffer)

            # Check for Mermaid block entry
            match = self.re_mermaid_block_start.search(s.out_buffer)

            if match:
                start, end = match.span()
                pre_block = s.out_buffer[:start]
                mermaid_start = s.out_buffer[end:]

                # Sanitize pre-block
                sanitized_pre = self.sanitize_text(pre_block)
                sanitized_pre = self.re_legacy_table.sub("", sanitized_pre)

                if sanitized_pre and not sanitized_pre.endswith("\n"):
                    sanitized_pre += "\n"

                # LATE BINDING: Store tag
                output_chunk = sanitized_pre
                s.pending_tag = "```mermaid"

                # Switch state
                s.is_inside = True
                s.is_fake_table = False
                s.buffer = mermaid_start
                s.out_buffer = ""

            else:
                # Rolling Buffer Logic
                s.out_buffer = self.sanitize_text(s.out_buffer)

                KEEP_CHARS = 30
                if len(s.out_buffer) > KEEP_CHARS * 2 or finish_reason:
                    if finish_reason:
                        to_flush = s.out_buffer
                        s.out_buffer = ""
                    else:
                        to_flush = s.out_buffer[:-KEEP_CHARS]
                        s.out_buffer = s.out_buffer[-KEEP_CHARS:]

                    to_flush = self.re_legacy_table.sub("", to_flush)
                    output_chunk = to_flush
                else:
                    output_chunk = ""

        return output_chunk


class Filter:
    class UserValves(BaseModel):
        enabled: bool = Field(
            default=True,
            description="Enable or disable the Mermaid Doctor filter transparently.",
        )
        inject_few_shots: bool = Field(
            default=True,
            description="Injects Mermaid few-shots into the prompt to guide micromodels and reduce hallucinations.",
        )
        inject_as_system_prompt: bool = Field(
            default=False,
            description="If enabled, injects the few-shots as a System prompt. If disabled, appends them to the last User prompt.",
        )
        strip_styles: bool = Field(
            default=True,
            description="Removes model-hallucinated colors, styles, and classDefs to keep UI consistent.",
        )

    def __init__(self):
        """
        Initialize the MITM Filter with empty processors and load valves.
        """

        self.valves = self.UserValves()
        self.processors = {}
        self.mermaid_sanitizer = MermaidSanitizer()

    def _get_valves(self, __user__: Optional[dict] = None) -> BaseModel:
        """
        Safely retrieves the UserValves from the __user__ dictionary if available,
        otherwise falls back to the default singleton valves.
        """
        if __user__ and "valves" in __user__ and isinstance(__user__["valves"], dict):
            try:
                return self.UserValves(**__user__["valves"])
            except Exception as e:
                print(f"Error parsing UserValves: {e}")
                return self.valves
        return self.valves

    def inlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """
        Intercepts the incoming request to verify if the filter is enabled and reset session state.
        Dynamically handles the injection of few-shots based on UserValves.
        """

        valves = self._get_valves(__user__)
        user_id = __user__.get("id", "default") if __user__ else "default"

        # Initialize processor for this request with empty state
        state = StreamState()

        self.processors[user_id] = MermaidStreamProcessor(
            state=state,
            mermaid_sanitizer=self.mermaid_sanitizer,
            template_sanitizer_fn=lambda x: x,  # No-op for text, just pass through
            debug_service=None,
        )

        # Spacing rule: empty line before if
        if not valves.enabled:
            self.processors[user_id].state.bypass = True
            return body

        # Filter is enabled: Disable bypass (default is False in StreamState, but explicit is better)
        self.processors[user_id].state.bypass = False

        messages = body.get("messages", [])

        # Spacing rule: empty line before if
        if not messages:
            return body

        # Spacing rule: empty line before if
        if valves.inject_few_shots:
            # Spacing rule: empty line before if
            if valves.inject_as_system_prompt:
                # Insert as a system message at the beginning
                body["messages"].insert(
                    0, {"role": "system", "content": FEW_SHOTS_TEMPLATE}
                )

            # Spacing rule: empty line before else
            else:
                last_msg = body["messages"][-1]

                # Spacing rule: empty line before if
                if last_msg.get("role") == "user":
                    last_msg["content"] += f"\n\n{FEW_SHOTS_TEMPLATE}"

        return body

    async def stream(self, event: dict, __user__: Optional[dict] = None) -> dict:
        """
        Man-in-the-Middle implementation using MermaidStreamProcessor.
        """

        user_id = __user__.get("id", "default") if __user__ else "default"
        valves = self._get_valves(__user__)

        # Auto-recover processor if missing (e.g. server restart during stream)
        if user_id not in self.processors:
            state = StreamState()
            state.bypass = (
                True  # Default to bypass for safety if not initialized via inlet
            )
            self.processors[user_id] = MermaidStreamProcessor(
                state=state,
                mermaid_sanitizer=self.mermaid_sanitizer,
                template_sanitizer_fn=lambda x: x,
                debug_service=None,
            )

        processor = self.processors[user_id]

        # Fast bypass
        if processor.state.bypass:
            return event

        choices = event.get("choices", [])
        if not choices:
            return event

        choice = choices[0]
        delta = choice.setdefault("delta", {})
        content = delta.get("content", "")
        finish_reason = choice.get("finish_reason")

        if not content and not finish_reason:
            return event

        # Delegate to Processor
        new_content = processor.process(content, finish_reason, valves)

        # Update Delta
        delta["content"] = new_content

        return event

    def outlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """
        Post-processing if needed. Currently just cleans up the processor.
        """
        user_id = __user__.get("id", "default") if __user__ else "default"

        # Optional: cleanup processor to free memory
        # if user_id in self.processors:
        #     del self.processors[user_id]

        return body
